config/routes.rb
Rails.application.routes.draw do
  root to: "pages#show", id: "home"

  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions"}
  resources :collections do
    member do
      post :sort
    end
  end
  resources :resource_collections, only: [:update]
  resources :resources do
    member do
      post :collect_one
    end
  end
  resources :users, only: [:index, :show]

  # Admins
  devise_for :admins, path: :admin, skip: :registrations
  namespace :admin do
    root to: "dashboard#index"
    resources :users, only: [:index, :show] do
      member do
        put :feature, defaults: { format: "json" }
      end
    end
    resources :collections do
      member do
        put :feature, defaults: { format: "json" }
      end
    end
    resources :resources
    resources :admins, only: :index
  end
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  include Slug
  include ActionView::Helpers #for #small_description

  has_many :resource_collections, dependent: :destroy
  has_many :resources, through: :resource_collections

  belongs_to :owner, class_name: "User", foreign_key: "user_id"

  scope :featured, ->(limit=5) { where.not(featured_at: nil).order(featured_at: :desc).limit(limit) }

  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :owner, presence: true

  def to_s
    name
  end

  def toggle_featured
    if featured_at.blank?
      touch(:featured_at)
    else
      update_attribute(:featured_at, nil)
    end
  end

  def small_description
    truncate(description, length: 56)
  end
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < AdminsController
  before_action :set_collection, only: [:show, :feature]

	authorize_resource
  
  def index
    @collections = Collection.all
  end

  def show
  end

  # PUT /admins/collections/:id/feature
  def feature
    if @collection.toggle_featured
      render json: { success: true }
    end
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

end

app/controllers/admins/collections_controller.rb
class Admins::CollectionsController < AdminsController
  before_action :set_collection, only: [:show, :feature]

	authorize_resource
  
  def index
    @collections = Collection.all
  end

  def show
  end

  # PUT /admins/collections/:id/feature
  def feature
    if @collection.toggle_featured
      render json: { success: true }
    end
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy, :sort]
  authorize_resource

  # GET /collections
  def index
    @collections = Collection.featured(20)
  end

  # GET /collections/1
  def show
    @resource_collections = @collection.resource_collections.includes(:resource).order("position")
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  def create
    @collection = current_user.collections.new(collection_params)

    if @collection.save
      redirect_to @collection, notice: 'Collection was successfully created.'
    else
      render :new
    end
  end

  # POST /collections/1/sort
  def sort
    params[:resource].each_with_index do |id, index|
      ResourceCollection.where({resource_id: id, collection_id: @collection.id}).update_all({position: index+1})
    end
    render nothing: true
  end

  # PATCH/PUT /collections/1
  def update
    if @collection.update(collection_params)
      redirect_to @collection, notice: 'Collection was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /collections/1
  def destroy
    @collection.destroy
    redirect_to current_user, notice: 'Collection was successfully destroyed.'
  end

  private
    def set_collection
      @collection = Collection.find(params[:id])
    end

    def collection_params
      params.require(:collection).permit(:name, :image, :description)
    end
end

app/views/collections/_card.html.haml
.panel.panel-default
  .panel-heading.clearfix
    %h3.panel-title.pull-left Collection Info
  .list-group
    .list-group-item
      %p.list-group-item-text Name
      %h4.list-group-item-heading= collection.name
    .list-group-item
      %p.list-group-item-text Owner
      %h4.list-group-item-heading= collection.owner
    .list-group-item
      %p.list-group-item-text Resources
      %h4.list-group-item-heading= collection.resources.count
    .list-group-item
      %p.list-group-item-text Created
      %h4.list-group-item-heading= collection.created_at
    .list-group-item
      %p.list-group-item-text Last Updated
      %h4.list-group-item-heading= collection.updated_at
    
    

app/views/collections/_form.html.haml
= simple_form_for(collection) do |f|
  = f.error_notification
  - if collection.image.present?
    .form-image.text-center
      = image_tag collection.image, class: "imgix-fluid"
  .form-inputs
    = f.input :name, required: true, autofocus: true, placeholder: "Enter the collection's name"
    = f.input :image, as: :file
    = f.input :description, placeholder: "Tell us more about this collection"
  .form-actions.text-right
    - if collection.id
      = link_to "Cancel", collection_path(collection), class: "btn btn-danger"
    = f.button :submit

app/views/collections/_table.html.haml
%table.table.table-compressed.table-hover.table-striped
  %thead
    %tr
      %th Name
      %th Resources
      %th Owner
      %th.text-right Actions
  %tbody.js-clickable-rows
    - collections.each do |collection|
      %tr{data: {href: "#{collection_path(collection)}"}}
        %td= collection.name
        %td= collection.resources.count
        %td= collection.owner
        %td.js-clickable-non.text-right
          .btn-group
            - if can? :update, collection
              = link_to edit_collection_path(collection), class: "btn btn-xs btn-primary" do
                %i.fa.fa-pencil
                Edit

app/views/collections/_tiles.html.haml
.collection-tiles
  - collections.each do |collection|
    = link_to collection_path(collection), class: 'collection-tile' do
      .collection-tile--header{style: "background-image:url(#{image_path collection.image})"}
        .collection-tile--curator
          %span.user-image
            = image_tag collection.owner.image
          %span= collection.owner
      .collection-tile--name
        %h3= collection.name
      .collection-tile--description= collection.small_description

app/views/collections/edit.html.haml
.page-header
  %h1 Editing Collection

.container
  = render 'form', collection: @collection

app/views/collections/index.html.haml
.page-header
  %h1 Featured Collections
  %h2 Curated resources by community leaders in the Triangle.

.container
  = render 'tiles', collections: @collections
  

app/views/collections/new.html.haml
.page-header
  %h1 New Collection

= render 'form', collection: @collection

app/views/collections/show.html.haml
.page-image-header{style: "background-image:url(#{image_path(@collection.image)});"}
  .page-image-header--shadow
    .container.page-image-header--heading
      .row
        .col-sm-offset-1.col-sm-10
          %h1
            = @collection
            - if can? :edit, @collection
              = link_to edit_collection_path(@collection) do 
                %i.fa.fa-pencil-square-o
          %h2.collection-description= @collection.description
          .page-image-header--heading--owner
            = link_to user_path(@collection.owner) do
              %span.user-image
                = image_tag @collection.owner.image
              %span= "by #{@collection.owner}"
      .row
        .col-sm-offset-5.col-sm-2
          - if can? :destroy, @collection
            = link_to @collection, class: "collection-delete", method: :delete, data: {confirm: "Are you sure you want to delete this collection?"} do
              %i.fa.fa-trash-o
              Delete Collection

.container
  = render 'resource_collections/list', resource_collections: @resource_collections