config/routes.rb
Rails.application.routes.draw do
  root to: "pages#show", id: "home"

  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions"}
  resources :collections do
    member do
      post :sort
    end
  end
  resources :resource_collections, only: [:update]
  resources :resources do
    member do
      post :collect_one
    end
  end
  resources :users, only: [:index, :show]

  # Admins
  devise_for :admins, path: :admin, skip: :registrations
  namespace :admin do
    root to: "dashboard#index"
    resources :users, only: [:index, :show] do
      member do
        put :feature, defaults: { format: "json" }
      end
    end
    resources :collections do
      member do
        put :feature, defaults: { format: "json" }
      end
    end
    resources :resources
    resources :admins, only: :index
  end
end

app/views/admin/_flashes.html.haml
- if flash.any?
  .container
    .row
      .col-sm-12
        - flash.each do |key, value|
          .alert.text-center.fade.in{class: "alert-#{key}", role: "alert"}
            = value
            %button.close{data: {dismiss: "alert"}}
              %i.fa.fa-times

app/views/admin/_navbar.html.haml
%nav.navbar.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#parkland-navbar", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Parkland Admin", root_path, class: "nav-logo navbar-brand"
    #parkland-navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: ('active' if controller_name == "users")}
          = link_to "Users", admin_users_path
        %li{class: ('active' if controller_name == "collections")}
          = link_to "Collections", admin_collections_path
        %li{class: ('active' if controller_name == "resources")}
          = link_to "Resources", admin_resources_path
        %li{class: ('active' if controller_name == "admins")}
          = link_to "Admins", admin_admins_path

      .navbar-right
        %ul.nav.navbar-nav
          - if admin_signed_in?
            %li
              = link_to destroy_admin_session_path, method: :delete, class: 'navbar-link' do
                %i.fa.fa-sign-out
                Sign out
          - else
            %li
              = link_to new_admin_session_path, class: 'navbar-link' do
                %i.fa.fa-sign-in
                Sign in
          