config/routes.rb
Rails.application.routes.draw do
  root to: "pages#show", id: "home"

  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions"}
  resources :collections do
    member do
      post :sort
    end
  end
  resources :resource_collections, only: [:update]
  resources :resources do
    member do
      post :collect_one
    end
  end
  resources :users, only: [:index, :show]

  # Admins
  devise_for :admins, path: :admin, skip: :registrations
  namespace :admin do
    root to: "dashboard#index"
    resources :users, only: [:index, :show] do
      member do
        put :feature, defaults: { format: "json" }
      end
    end
    resources :collections do
      member do
        put :feature, defaults: { format: "json" }
      end
    end
    resources :resources
    resources :admins, only: :index
  end
end

app/models/user.rb
  class User < ActiveRecord::Base
  include Slug

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :alphabetical, -> { order(:name) }
  scope :featured, ->(limit=5) { where.not(featured_at: nil).order(featured_at: :desc).limit(limit) }

  mount_uploader :image, ImageUploader

  has_many :collections
  has_many :resources

  validates :email, presence: true
  validates :name, presence: true

  def to_s
    name
  end

  def toggle_featured
    if featured_at.blank?
      touch(:featured_at)
    else
      update_attribute(:featured_at, nil)
    end
  end

end

app/views/resources/_card.html.haml
.panel.panel-default
  .panel-heading.clearfix
    %h3.panel-title.pull-left Resource Info
    .pull-right
      - if can? :edit, resource
        = link_to edit_resource_path(resource), class: 'btn btn-warning btn-xs' do
          %i.fa.fa-pencil
          edit
  .list-group
    .list-group-item
      %p.list-group-item-text Name
      %h4.list-group-item-heading= resource.name
    .list-group-item
      %p.list-group-item-text Type
      %h4.list-group-item-heading= resource.type
    .list-group-item
      %p.list-group-item-text Owner
      %h4.list-group-item-heading= resource.owner
    .list-group-item
      %p.list-group-item-text Link
      %h4.list-group-item-heading= resource.href
    .list-group-item
      %p.list-group-item-text Description
      %h4.list-group-item-heading= resource.description
    .list-group-item
      %p.list-group-item-text Created
      %h4.list-group-item-heading= resource.created_at
    .list-group-item
      %p.list-group-item-text Last Updated
      %h4.list-group-item-heading= resource.updated_at
    - if can? :collect_one, @resource and current_user.collections.count > 0
      .list-group-item
        %p.list-group-item-text Collect
        - @resource = @resource.becomes(Resource)
        = form_for @resource, url: collect_one_resource_path(@resource), remote: true, html: {method: :post, class: 'list-group-item-heading'} do |f|
          = f.collection_select(:collection_ids, current_user.collections, :id, :to_s, {}, {multiple: true, class: "selectpicker resource-collection-ids"})
    

app/views/resources/_company_form.html.haml
= simple_form_for(resource) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name, placeholder: "Enter the company's name", required: true
    = f.input :href, label: "Link", placeholder: "http://www...", required: true
    = f.input :image, as: :file
    = f.input :description, placeholder: "Describe the company briefly"
    = f.hidden_field :type, value: "Company"
  .form-actions.text-right
    = f.button :submit

app/views/resources/_form.html.haml
- resource = resource.becomes(Resource)
= simple_form_for(resource, html: {class: 'form-horizontal'}, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean}) do |f|
  = f.error_notification
  .row
    .col-md-2
    .col-md-8
      - if resource.image.present?
        .form-image.text-center
          = image_tag resource.image, class: "imgix-fluid"
      .form-inputs
        = f.input :name
        = f.input :href, label: "Link", placeholder: "http://www..."
        = f.input :type, collection: ["Person", "Company"], include_blank: false
        = f.input :description, placeholder: "Describe the resource briefly"
        = f.input :image, as: :file
      .form-actions.text-right
        - if resource.id
          = link_to "Cancel", resource_path(resource), class: "btn btn-danger"
        = f.button :submit

app/views/resources/_list.html.haml
%ul.resource-items
  - resources.each do |resource|
    - resource = resource.becomes(Resource)
    %li.resource-item{data: {href: "#{resource_path(resource)}"}}
      .resource-item--rank= resource.collections_count
      .resource-item--thumbnail{style: "background-image:url(#{image_path(resource.image)});"}
      .resource-item--text
        = link_to resource, resource, class: "resource-item--text--name"
        %span.resource-item--text--description= resource.description
        .resource-item--text--data
          %span.resource-item--text--data--type= resource.type
          %span.resource-item--text--data--tags
      .resource-item--actions
        .resource-item--actions--collect
          - if can? :collect_one, resource and current_user.collections.count > 0
            = form_for resource, url: collect_one_resource_path(resource), remote: true, html: {method: :post} do |f|
              = f.collection_select(:collection_ids, current_user.collections, :id, :to_s, {}, {multiple: true, class: "selectpicker resource-collection-ids"})
        .resource-item--actions--owner
          = link_to resource.owner, class: "user-image" do
            %span.user-image
              .user-image--badge
              = image_tag resource.owner.image

app/views/resources/_person_form.html.haml
= simple_form_for(resource) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name, placeholder: "Enter the individual's name", required: true
    = f.input :href, label: "Link", placeholder: "http://www...", required: true
    = f.input :image, as: :file
    = f.input :description, placeholder: "Describe the individual briefly"
    = f.hidden_field :type, value: 'Person'
  .form-actions.text-right
    = f.button :submit

app/views/resources/_table.html.haml
%table.table.table-compressed.table-hover.table-striped
  %thead
    %tr
      %th Name
      %th Link
      %th Owner
      %th Times Collected
      - if can? :collect_one, Resource
        %th.text-right Collect
  %tbody.js-clickable-rows
    - resources.each do |resource|
      %tr{data: {href: "#{resource_path(resource)}"}}
        - if resource.type == "Person"
          %td
            %i.fa.fa-user
        - else
          %td
            %i.fa.fa-users
        %td= resource.name
        %td= resource.href
        %td= resource.owner
        %td= resource.collections.count
        - if can? :collect_one, Resource
          %td.js-clickable-non.text-right
            - if can? :collect_one, resource and current_user.collections.count > 0
              - resource = resource.becomes(Resource)
              = form_for resource, url: collect_one_resource_path(resource), remote: true, html: {method: :post} do |f|
                = f.collection_select(:collection_ids, current_user.collections, :id, :to_s, {}, {multiple: true, class: "selectpicker resource-collection-ids"})

app/views/resources/collect.js.erb
console.log("successfully updated user's collections.");

app/views/resources/collect_one.js.erb
console.log("successfully updated user's collections.");

app/views/resources/edit.html.haml
.page-header
  %h1 Editing Resource

.container
  = render 'form', resource: @resource

app/views/resources/index.html.haml
.container
  .page-header
    %h1 Top Resources
    %h2 The most popular resources in the Triangle.
  = render 'list', resources: @resources

app/views/resources/new.html.haml
.page-header
  %h1 New Resource

.container
  = render 'form', resource: @resource

app/views/resources/show.html.haml
.page-image-header{style: "background-image:url(#{image_path(@resource.image)});"}
  .page-image-header--shadow
    .container.page-image-header--heading
      .row
        .col-sm-offset-1.col-sm-10
          %h1
            = @resource
            - if can? :edit, @resource
              = link_to edit_resource_path(@resource) do 
                %i.fa.fa-pencil-square-o
          %h2.resource-description= @resource.description
          .page-image-header--heading--owner
            = link_to user_path(@resource.owner) do
              %span.user-image
                = image_tag @resource.owner.image
              %span= "shared by #{@resource.owner}"

.container
  .resource-info
    %h1= link_to "Click here to visit website", @resource.href, target: "_blank"
    - if can? :collect_one, resource and current_user.collections.count > 0
      = form_for resource, url: collect_one_resource_path(resource), remote: true, html: {method: :post} do |f|
        = f.collection_select(:collection_ids, current_user.collections, :id, :to_s, {}, {multiple: true, class: "selectpicker resource-collection-ids"})
    %p= "Last updated #{time_ago_in_words @resource.updated_at} ago"
  - if @collections.present?
    .resource-collections
      %h2= "#{@collections.count} Collections"
      = render 'collections/tiles', collections: @collections
  .resource-comingsoon
    %h3 More information and features coming soon
    %p Want to see something specific here? Join our chat community to suggest them.